// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Walkabouts.Repository.Context;

namespace Walkabouts.Repository.Migrations
{
    [DbContext(typeof(WalkaboutsDbContext))]
    [Migration("20210704213450_updateSeedData")]
    partial class updateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.AppRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ShoppingCartId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.PaymentOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UserWalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserWalletId");

                    b.ToTable("PaymentOption");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 137, DateTimeKind.Local).AddTicks(7717),
                            Description = "",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 137, DateTimeKind.Local).AddTicks(7764),
                            ProductName = "Samsung 50 inch",
                            RefId = new Guid("d6b3cc59-c695-40ca-bb6a-fc20be64978f"),
                            StockLevel = 15,
                            UnitPrice = 3400m
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(135),
                            Description = "Every single American needs to read Michael Knowles’s Speechless. I don’t mean ‘read it eventually.’ I mean: stop what you’re doing and pick up this boo",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(139),
                            ProductName = "Speechless: Controlling Words, Controlling Minds Hardcover",
                            RefId = new Guid("5e38f72c-a107-43f6-9533-d19a8fe56243"),
                            StockLevel = 11,
                            UnitPrice = 24.49m
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(154),
                            Description = "Next-level Hardware - Make every move count with a blazing-fast processor and our highest-resolution display\r\nAll-In-One Gaming - With backward compatibility, you can explore new titles and old favorites in the expansive Quest content library",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(156),
                            ProductName = "Oculus Quest 2 — Advanced All-In-One Virtual Reality Headset ",
                            RefId = new Guid("9989e3bb-7341-48f6-a834-e95517311ba8"),
                            StockLevel = 5,
                            UnitPrice = 299m
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(164),
                            Description = "The Real 4K TV for all your entertainment needsLG UHD TV was made to entertain by taking everything you watch to a new level. Whether it's cinema, sports, or games, it delivers real 4K images with vivid color and fine detail. Enjoy more realistic images in four times the resolution of Full HD.",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(166),
                            ProductName = "LG 65''Smart UHD 4K Satellite Ai ThinQ TV ",
                            RefId = new Guid("26724d46-2d9a-4707-bfcf-c44f1da2fd07"),
                            StockLevel = 15,
                            UnitPrice = 378.89m
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(173),
                            Description = "2 Outlets 3 USB Charging Ports(3.1A, 15W)",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(174),
                            ProductName = "Power Strip with USB ",
                            RefId = new Guid("715dca48-ac35-4623-8a2a-035fe7f94e77"),
                            StockLevel = 15,
                            UnitPrice = 9.38m
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(181),
                            Description = "",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(183),
                            ProductName = "SUNGAIT Ultra Lightweight Rectangular Polarized Sunglasses",
                            RefId = new Guid("65eef082-0075-4109-846a-2066e4114985"),
                            StockLevel = 15,
                            UnitPrice = 300m
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(189),
                            Description = "[Face Masks]: Mouth Face Mask 3-ply With Elastic Earloops for Day-to-day protection\r\n                                      [Disposable Masks]: The disposable face mask is made from a supportive and powerful 3 - layered fabric for 3 - Way filter\r\n                                      [Disposable Face Masks]: Designed for a softer and smoother feel for Breathability all day long",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(191),
                            ProductName = "Disposable Face Masks, Face Masks of 50 Pack Disposable Mask",
                            RefId = new Guid("929044e3-c466-4272-b7ca-485e9d395ee9"),
                            StockLevel = 100,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(252),
                            Description = "Lightweight feature makes it portable for using anywhere; Compact design performs well on any occasion; Perfect for RVs, boats, kitchens, tea shops, KTVs, offices, bars, restaurants, parties, gatherings, holidays, etc",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(254),
                            ProductName = "VIVOHOME Electric Portable Compact Countertop Automatic Ice Cube Maker Machine",
                            RefId = new Guid("26e0367c-4d09-4884-a541-7be9425a6f8b"),
                            StockLevel = 73,
                            UnitPrice = 96.78m
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(263),
                            Description = "With unique inspirational quote and time marker on it, this water bottle is great for measuring your daily intake of water, reminding you stay hydrated and drink enough water throughout the day. A must have for any fitness goals including weight loss and overall health.",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(265),
                            ProductName = "Venture Pal Large 1 Gallon/128 OZ Motivational BPA Free Leakproof Water Bottle with Straw & Time Marker",
                            RefId = new Guid("709dda71-a97d-4db9-aa2d-09b6e219df23"),
                            StockLevel = 57,
                            UnitPrice = 14.99m
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(273),
                            Description = "High pressure rainfall shower head: Our luxury bathroom rainhead is the perfect replacement that will jet out high-pressure rain of hot water so your whole body is doused with the downpour. You won’t go back to a normal shower again",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(275),
                            ProductName = "SparkPod Shower Head",
                            RefId = new Guid("93801d59-5da9-4a8d-ab2d-5c71e41ea1fa"),
                            StockLevel = 132,
                            UnitPrice = 29.72m
                        },
                        new
                        {
                            Id = 11L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(282),
                            Description = "The iPhone stand is made of high-quality aluminum alloy with a nice finish. Stable and easy to watch Youtube or FaceTime. Besides, rubber non-slip pads protect the surface of your phone case and desk from scratches.",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(284),
                            ProductName = "Lamicall Cell Phone Stand, Phone Dock",
                            RefId = new Guid("273b710f-a377-4041-97b4-d14b5a821ec6"),
                            StockLevel = 84,
                            UnitPrice = 7.99m
                        },
                        new
                        {
                            Id = 12L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(290),
                            Description = "AMD Ryzen 7 4700U Octa-Core Mobile Processor (Up to 4.1 GHz) with Radeon Graphics; 8GB LPDDR4 Memory; 512GB PCIe NVMe SSD\r\n                                        14 Full HD Widescreen IPS LED - backlit display(1920 x 1080 resolution; 16:9 aspect ratio)\r\n                                        Intel wireless Wi - Fi 6 AX200 802.11ax; HD webcam(1280 x 720); Backlit keyboard; Fingerprint reader",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(292),
                            ProductName = "Acer Swift 3 Thin & Light Laptop, 14 Full HD IPS",
                            RefId = new Guid("42fc3261-b28c-4240-83b0-d89d58a386be"),
                            StockLevel = 5,
                            UnitPrice = 618.92m
                        },
                        new
                        {
                            Id = 13L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(298),
                            Description = "The 10.1 inch Tablet PC is equipped with high-performance 1.6GHz Quad-Core processor & Android 9.0 operating systems, capable of guaranteeing an extremely fluid gaming experience and a fast multimedia experience. With 2GB RAM and 32 GB internal storage, it's very suitable for running a number of entertainment applications without stucking, such as Netflix, Amazon Prime and Youtube",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(300),
                            ProductName = "Tablet 10.1 inch Android 9.0 Tablet PC",
                            RefId = new Guid("e148ed17-2c1b-49c6-aae7-ab8fc8de26a8"),
                            StockLevel = 39,
                            UnitPrice = 99.99m
                        },
                        new
                        {
                            Id = 14L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(306),
                            Description = "iPhone 7 is the 10th generation of Apple (Apple) mobile phone, released at 1:00 am Beijing time on September 8, 2016 at the San Francisco Graham Municipal Auditorium 2016 Apple Autumn New Product Launch Conference",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(308),
                            ProductName = "Apple IPhone 7 4.7 Inch 2GB",
                            RefId = new Guid("94b9e8f3-3b30-4f3e-8c02-71ef2c8f58e7"),
                            StockLevel = 46,
                            UnitPrice = 230.3m
                        },
                        new
                        {
                            Id = 15L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(314),
                            Description = "3 Play Styles: TV Mode, Tabletop Mode, Handheld Mode\r\n                                         6.2-inch, multi-touch capacitive touch screen\r\n                                         4.5-9+ Hours of Battery Life will vary depending on software usage conditions\r\n                                         Connects over Wi-Fi for multiplayer gaming; Up to 8 consoles can be connected for local wireless multiplayer",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(316),
                            ProductName = "Nintendo Switch with Neon Blue and Neon Red Joy‑Con",
                            RefId = new Guid("53b4ea1d-0e72-4953-a3bd-715d69027a15"),
                            StockLevel = 15,
                            UnitPrice = 314.95m
                        },
                        new
                        {
                            Id = 16L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(340),
                            Description = "Versatile light/fan: Ultra Bright 18 individual low powered LED bulbs. The fan has high and low settings to provide nice air circulation and lit up the tent nicely. You can orient in so many positions.",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(343),
                            ProductName = "Odoland Portable LED Camping Lantern with Ceiling Fan",
                            RefId = new Guid("8eb04d82-3697-4b01-9bfa-17442339fd64"),
                            StockLevel = 15,
                            UnitPrice = 16.67m
                        },
                        new
                        {
                            Id = 17L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(349),
                            Description = "Used on Drill Glass,Wood,Tile Bottles,Blocks Jars, Ceramic,Slate Mable, Granite Light Stone, and other hard surfaces",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(351),
                            ProductName = "Diamond Drill Bit Set Hole, 15PCS Hole Saw Set",
                            RefId = new Guid("1842b564-632e-4839-8b91-f8ec02cffbd0"),
                            StockLevel = 186,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 18L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(359),
                            Description = "Our hammocks are well made of 210T parachute nylon fabric, to be soft while breathable and quick dry, triple stitching to strength durability and security.",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(361),
                            ProductName = "Camping Hammock for Outdoors Travel Backpacking",
                            RefId = new Guid("0407eba9-4f6a-481b-b061-2a9dd1c823b3"),
                            StockLevel = 95,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 19L,
                            CreatedBy = 0L,
                            CreatedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(367),
                            Description = "tool is self-opening; revolving punch is powerful and easy, giving you the capability to cleaning punch holes every time",
                            Featured = false,
                            ModifiedOn = new DateTime(2021, 7, 4, 22, 34, 49, 138, DateTimeKind.Local).AddTicks(369),
                            ProductName = "General Tools 72 Leather Hole Punch Tool",
                            RefId = new Guid("53cb842d-0f5f-4255-87a0-8b425f279387"),
                            StockLevel = 83,
                            UnitPrice = 9.25m
                        });
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.ProductReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumOfStars")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<long?>("ProductId1")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.ShoppingCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("CartTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ShoppingCartId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShoppingCartId1")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserWalletId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserWalletId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId1");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserWalletId1");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.UserWallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("UserWallets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Walkabouts.Data.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.OrderItem", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.ShoppingCart", null)
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ShoppingCartId");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.PaymentOption", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.UserWallet", null)
                        .WithMany("PaymentOptions")
                        .HasForeignKey("UserWalletId");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.ProductReview", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.ShoppingCart", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Walkabouts.Data.Domain.ShoppingCart", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.UserProfile", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.ShoppingCart", "ShoppingCart")
                        .WithMany()
                        .HasForeignKey("ShoppingCartId1");

                    b.HasOne("Walkabouts.Data.Domain.AppUser", "AppUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("Walkabouts.Data.Domain.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Walkabouts.Data.Domain.UserWallet", "UserWallet")
                        .WithMany()
                        .HasForeignKey("UserWalletId1");

                    b.Navigation("AppUser");

                    b.Navigation("ShoppingCart");

                    b.Navigation("UserWallet");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.UserWallet", b =>
                {
                    b.HasOne("Walkabouts.Data.Domain.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Walkabouts.Data.Domain.UserWallet", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.AppUser", b =>
                {
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.Product", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartItems");
                });

            modelBuilder.Entity("Walkabouts.Data.Domain.UserWallet", b =>
                {
                    b.Navigation("PaymentOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
